POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/69727836-0a3b-4b9c-9e54-67862be65a43/attendees
Content-Type: application/json

{
  "name": "Alan Gonçalves",
  "email": "lnjnr92@gmail.com"
}

###

GET http://localhost:3333/events/69727836-0a3b-4b9c-9e54-67862be65a43

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/3/check-in
###

GET http://localhost:3333/events/69727836-0a3b-4b9c-9e54-67862be65a43/attendees