POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/086fe9f6-c17f-426b-9473-3f278c350008/attendees
Content-Type: application/json

{
  "name": "Alan Gonçalves",
  "email": "lnjnr92@gmail.com"
}

###

GET http://localhost:3333/events/e94fdbb8-93d0-4207-bf56-8a5a8bc7fe00

###

GET http://localhost:3333/attendees/4/badge